workspace:
  launch:
    button:
      name: 🛫 起飞
      description: 💪 逐步迈向运维的四个现代化：规范化，标准化，高效化，优雅化
      hoverImage: https://cnb.cool/66666/resource/-/git/raw/main/img/qifei.gif
    cpus: 16
    disabled: false
    autoOpenWebIDE: false

issue:
  button:
    description: 🙋🏻‍♀️ I Have A Question
    hoverImage: "https://cnb.cool/66666/resource/-/git/raw/main/img/jushou.jpg"

fork:
  button:
    description: 🫵 年轻人，你很眼光
    hoverImage: "https://cnb.cool/66666/resource/-/git/raw/main/img/trump.gif"